version: "3"

services:
  gitea-gui:
    image: gitea/gitea:1.10.0
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - ROOT_URL=http://<Serveur URL>:3000
      - DB_TYPE=postgres
      - DB_HOST=gitea-db:5432
      - DB_NAME=gitea
      - DB_USER=gitea
      - DB_PASSWD=gitea
    restart: always
    volumes:
      - ./gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "222:22"
    links:
      - gitea-db

  gitea-db:
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_USER=gitea
      - POSTGRES_PASSWORD=gitea
      - POSTGRES_DB=gitea
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432

  drone-gui:
    image: drone/drone:1.6.2
    ports:
      - 8000:8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./volumes/drone:/var/lib/drone/
    restart: always
    depends_on:
      - gitea-gui
    links:
      - gitea-gui
    environment:
      - DRONE_AGENTS_ENABLED=true
      - DRONE_GITEA_CLIENT_ID=<OAuth2 ID client>
      - DRONE_GITEA_CLIENT_SECRET=<OAuth2 secret client>
      - DRONE_GITEA_SERVER=http://<Server URL>:3000
      - DRONE_GIT_ALWAYS_AUTH=false
      - DRONE_TLS_AUTOCERT=false
      - DRONE_SERVER_PORT=:8000
      - DRONE_SERVER_HOST=<Server URL>:8000
      - DRONE_SERVER_PROTO=http
      - DRONE_RPC_SECRET=secret
      - DRONE_RUNNER_NETWORKS=gitea-drone_default

  drone-runner-docker:
    image: drone/drone-runner-docker:latest
    restart: always
    depends_on:
      - drone-gui
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    links:
      - drone-gui
      - gitea-gui
    environment:
      - DRONE_RPC_HOST=<Server URL>:8000
      - DRONE_RPC_PROTO=http
      - DRONE_RPC_SECRET=secret
      - DRONE_RUNNER_NAME=drone-runner-docker
      - DRONE_UI_USERNAME=test
      - DRONE_UI_PASSWORD=test
      - DRONE_RUNNER_NETWORKS=gitea-drone_default

volumes:
  gitea-app:
  gitea-db:
